// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc7K_sIAfVSzOur_EukHw-VldeQDbmfQA',
    appId: '1:454939057507:android:adb8252b06059e675f0756',
    messagingSenderId: '454939057507',
    projectId: 'liveprice-5ed48',
    databaseURL: 'https://liveprice-5ed48-default-rtdb.firebaseio.com',
    storageBucket: 'liveprice-5ed48.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnCfG4ngEJHKKG8s_s5mV3dpPukwgJSdg',
    appId: '1:454939057507:web:120a4a32a95d84705f0756',
    messagingSenderId: '454939057507',
    projectId: 'liveprice-5ed48',
    authDomain: 'liveprice-5ed48.firebaseapp.com',
    databaseURL: 'https://liveprice-5ed48-default-rtdb.firebaseio.com',
    storageBucket: 'liveprice-5ed48.firebasestorage.app',
    measurementId: 'G-DBT7PV35J7',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7hhgOXWaPlFi0MmP3hIxmu3wQxCMMDYM',
    appId: '1:454939057507:ios:e07e1842d8d63dfc5f0756',
    messagingSenderId: '454939057507',
    projectId: 'liveprice-5ed48',
    databaseURL: 'https://liveprice-5ed48-default-rtdb.firebaseio.com',
    storageBucket: 'liveprice-5ed48.firebasestorage.app',
    androidClientId: '454939057507-t63sitqgn7l2kmqjtnq16i9fsij9g54j.apps.googleusercontent.com',
    iosClientId: '454939057507-olcg1tdlagsbo2fhb1kp661a5im26p0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveprice',
  );
}
