name: liveprice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.6.1
  http: ^1.2.0
  firebase_core: ^3.0.0
  firebase_app_check: ^0.3.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.0.0
  file_picker: ^13.1.0
  flutter_svg: ^2.0.10
  shared_preferences: ^2.5.5
  firebase_messaging: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcompic/welcompic1.json